mkdir backend
cd backend
mkdir app
mkdir app/api
mkdir app/api/endpoints
mkdir app/api/models
mkdir app/api/utils
mkdir app/core
mkdir app/core/embedding
mkdir app/core/llm
mkdir app/core/rag
mkdir app/core/vector_database
mkdir app/core/orchestration
mkdir app/data
mkdir app/db
mkdir app/utils
mkdir tests
mkdir tests/api
mkdir tests/core
touch app/__init__.py
touch app/api/__init__.py
touch app/api/endpoints/__init__.py
touch app/api/endpoints/chat.py
touch app/api/endpoints/data.py
touch app/api/models/__init__.py
touch app/api/utils/__init__.py
touch app/core/__init__.py
touch app/core/embedding/__init__.py
touch app/core/embedding/embedding_service.py
touch app/core/llm/__init__.py
touch app/core/llm/llm_service.py
touch app/core/rag/__init__.py
touch app/core/rag/rag_pipeline.py
touch app/core/vector_database/__init__.py
touch app/core/vector_database/vector_db_service.py
touch app/core/orchestration/__init__.py
touch app/core/orchestration/external_apis.py
touch app/core/orchestration/chart_generation.py
touch app/data/.gitkeep
touch app/db/__init__.py
touch app/db/database.py
touch app/db/models.py
touch app/config.py
touch app/utils/__init__.py
touch app/utils/utils.py
touch tests/__init__.py
touch tests/api/__init__.py
touch tests/core/__init__.py
touch main.py
touch requirements.txt
touch .gitignore
touch README.md